---
- name: Remediate
  hosts: "{{ upgrade_group | default(omit) }}"
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true
  tasks:
    - name: Show current and target RHEL releases
      ansible.builtin.debug:
        msg:
          - "Current version of RHEL is {{ ansible_distribution_major_version }}"
          - "Target version of RHEL is {{ ipu_target | default('Not defined') }}"

    - name: If already at target major release exit this playbook
      ansible.builtin.meta: end_play
      when:
        - ipu_target is defined
        - ansible_distribution_major_version | int == ipu_target | int

    - name: "Remediate rhel7 systems"
      when: ansible_distribution_major_version | int == 7
      ansible.builtin.import_tasks: remediate_rhel7.yml
    - name: "Remediate rhel8 systems"
      when: ansible_distribution_major_version | int == 8
      ansible.builtin.import_tasks: remediate_rhel8.yml

  handlers:
    - name: "Restart sshd"
      ansible.builtin.service:
        name: sshd
        state: restarted
    - name: "Restart firewalld"
      ansible.builtin.service:
        name: firewalld
        state: restarted
...
