---
- name: Wait for connection
  ansible.builtin.wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300

- name: Check for leapp utility
  ansible.builtin.stat:
    path: /usr/bin/leapp
  register: leapp_utility_check

- name: Check status of /etc/firewalld/firewalld.conf
  ansible.builtin.stat:
    path: /etc/firewalld/firewalld.conf
  register: firewalld_conf_file

- name: Configure AllowZoneDrifting to no if firewalld config file exists
  ansible.builtin.lineinfile:
    path: "/etc/firewalld/firewalld.conf"
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
    state: present
  loop:
    - {key: "AllowZoneDrifting", value: "no"}
  notify:
    - Restart firewalld
  when:
    - firewalld_conf_file.stat.isreg is defined

- name: Configure sshd
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - {key: "PermitRootLogin", value: "yes #rjo-override"}
  notify:
    - Restart sshd
...
